version: 0.1
phases:
  install:
    commands:
      - ls
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambda-pipline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml