AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  DrawOverImageGraphqlAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: server.lambda_handler
      Runtime: nodejs8.10
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::966653973445:role/service-role/DrawOverImage'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: ap-southeast-2