AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  DrawOverImageGraphqlAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: server.lambda_handler
      Runtime: nodejs8.10
      CodeUri: ./LambdaCode
      Description: 'Lambda function for Graphql Backend'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::966653973445:role/service-role/DrawOverImage'
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
        PostRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
        GraphiqlGetRequest:
          Type: Api
          Properties:
            Path: /graphiql
            Method: get
      Environment:
        Variables:
          REGION: us-east-1