AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    Cors:
      AllowOrigin: "'redacted'"
      AllowHeaders: "'Accept,Origin,Content-Type,X-Amz-Date,X-Requested-With,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
      AllowMethods: "'POST,GET,OPTIONS'"

Resources:
  DrawOverImageGraphqlAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: server.lambda_handler
      Runtime: nodejs8.10
      CodeUri: ./LambdaCode
      Description: 'Lambda function for Graphql Backend'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::966653973445:role/service-role/DrawOverImage'
      Events:
        GetRequest:
          Type: Api
          Properties:
            Path: /graphql
            Method: get
      Environment:
        Variables:
          REGION: us-east-1